# numpy('~'*50)

1.ndarray

In [2]:
import numpy as np

In [6]:
#array 생성
test_array = np.array([1,4,5,8],float)
test_array

array([1., 4., 5., 8.])

In [7]:
test_array[3]

8.0

In [9]:
test_array[2:]

array([5., 8.])

In [10]:
test_array.dtype, test_array.shape

(dtype('float64'), (4,))

In [17]:
test_array = np.array([1,2,"5",4.2])
test_array

array(['1', '2', '5', '4.2'], dtype='<U11')

In [18]:
test_array = np.array([1,2,"5",4.2], float)
test_array

array([1. , 2. , 5. , 4.2])

## array shape

In [25]:
#vetor(1차원)
test_array=np.array([1,4,5,8],float)
test_array.shape                

(4,)

In [30]:
matrix=([1,2,5,8],[2,3,4,9],[4,5,6,7])
np.array(matrix,int).shape    

(3, 4)

In [31]:
matrix

([1, 2, 5, 8], [2, 3, 4, 9], [4, 5, 6, 7])