# numpy('~'*50)

1.ndarray

In [2]:
import numpy as np

In [6]:
#array 생성
test_array = np.array([1,4,5,8],float)
test_array

array([1., 4., 5., 8.])

In [7]:
test_array[3]

8.0

In [9]:
test_array[2:]

array([5., 8.])

In [10]:
test_array.dtype, test_array.shape

(dtype('float64'), (4,))

In [17]:
test_array = np.array([1,2,"5",4.2])
test_array

array(['1', '2', '5', '4.2'], dtype='<U11')

In [18]:
test_array = np.array([1,2,"5",4.2], float)
test_array

array([1. , 2. , 5. , 4.2])

## array shape

In [25]:
#vetor(1차원)
test_array=np.array([1,4,5,8],float)
test_array.shape                

(4,)

In [30]:
matrix=([1,2,5,8],[2,3,4,9],[4,5,6,7])
np.array(matrix,int).shape    

(3, 4)

In [31]:
matrix

([1, 2, 5, 8], [2, 3, 4, 9], [4, 5, 6, 7])

###reshape

In [34]:
test_matrix=[[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [35]:
np.array(test_matrix).reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
np.array(test_matrix).reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [43]:
test_matrix=[[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[6,7,8,9]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a=np.array([[1,2,3],[4,5,6]],int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a[0,0]

1

In [47]:
a[1,2]

6

In [50]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [51]:
a[1,1:3]

array([7, 8])

## creation

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

###list 사용시 에러 그래서 tolist 사용!

In [55]:
np.zeros(shape=(10),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [56]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
test_matrix=np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [59]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [60]:
###단위행렬

In [61]:
np.identity(n=3,dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [62]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#대각행렬의 값을 추출

In [64]:
matrix=np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [65]:
np.diag(matrix,k=1)

array([1, 5])

In [67]:
np.random.seed(1000)  #시드로 난수 생성초기값 지정

In [68]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.65358959, 0.11500694, 0.95028286, 0.4821914 , 0.87247454],
       [0.21233268, 0.04070962, 0.39719446, 0.2331322 , 0.84174072]])

In [71]:
np.random.binomial(20,0.5,10)

array([ 8, 11,  9,  8, 11,  7, 13, 14, 13, 10])

###np.random.poisson(lam. size)		# 포아송 분포
###np.random.standard_t(df, size)		# t-분포
###np.random.f(dfnum, dfden, size)		# F-분포

In [73]:
#sum


test_array = np.arange(1,11)
test_array.sum(dtype=np.float)

55.0

In [75]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
test_array.sum()

78

In [77]:
test_array.sum(axis=0) ##

array([15, 18, 21, 24])

In [78]:
test_array.sum(axis=1)

array([10, 26, 42])

In [79]:
test_array=np.arange(1,25).reshape(2,3,4)
test_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [81]:
test_array.sum(axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [82]:
test_array.sum(axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [83]:
test_array.sum(axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

# 평균 표준편차.
   

In [88]:
test_array = np.arange(1,13).reshape(3,4)

In [90]:
test_array.mean()

6.5

In [91]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [93]:
test_array.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [94]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [95]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

# Concatenate!


In [96]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [98]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [99]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
c=np.array([7,8])
c

array([7, 8])

In [103]:
np.vstack((7,8))

array([[7],
       [8]])

In [104]:
##ex)


np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [106]:
b = np.array([[5],[6]])
b

array([[5],
       [6]])

In [107]:
np.hstack((a,b))

array([[1, 2, 5],
       [3, 4, 6]])

In [109]:
c=np.array([[7,8]])
c.T                         #행렬바꾸기 T=전치행렬

array([[7],
       [8]])

In [110]:
np.hstack((a,c.T))

array([[1, 2, 7],
       [3, 4, 8]])

In [111]:
np.concatenate((a,c.T),axis=1)

array([[1, 2, 7],
       [3, 4, 8]])

# 7. Array operation

In [119]:
test_a = np.array([[1,2,3], [4,5,6]], float)
test_b = np.arange(1,7).reshape(2,3)

In [120]:
test_a+test_b

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [121]:
test_a-test_b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [122]:
test_a*test_b

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [123]:
test_a/test_b

array([[1., 1., 1.],
       [1., 1., 1.]])

## dot product (행렬의 곱)
#(l,m)*(m,n)->(l,n)

In [124]:
test_a=np.arange(1,7).reshape(2,3)
test_a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
test_b=np.arange(7,13).reshape(3,2)
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [130]:
test_a.dot(test_b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [135]:
test_a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [136]:
test_a

array([[1, 2],
       [3, 4],
       [5, 6]])

NameError: name 'scalar' is not defined

In [139]:
test_matrix = np.array([[1,2,3], [4,5,6]], float)
scalar = 3

In [140]:
test_matrix + scalar 

array([[4., 5., 6.],
       [7., 8., 9.]])

In [141]:
test_matrix – scalar

SyntaxError: invalid character in identifier (<ipython-input-141-d4237ce6963a>, line 1)

In [142]:
test_matrix * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [143]:
test_matrix / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [144]:
test_matrix // scalar

array([[0., 0., 1.],
       [1., 1., 2.]])

In [146]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [147]:
test_matrix = np.arange(1,13).reshape(4,3)

In [150]:
test_vector = np.arange(10,40,10)
test_vector

array([10, 20, 30])

In [149]:
test_matrix + test_vector


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [152]:
a=np.arange(1,5).reshape(4,1)
a

array([[1],
       [2],
       [3],
       [4]])

In [154]:
b=np.arange(10,40,10)
b

array([10, 20, 30])

In [156]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

# All & Any

In [157]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [160]:
np.any(a<8)           #or 조건

True

In [161]:
np.any(a<0)

False

In [162]:
np.all(a>8)                       #and 조건

False

In [163]:
np.all(a<10)

True

In [164]:
test_a=np.array([1,3,0],float)
test_b=np.array([5,2,1],float)

In [166]:
test_a>test_b

array([False,  True, False])

In [169]:
test_a==test_b

array([ True,  True,  True])

In [170]:
(test_a>test_b).any()

False

In [171]:
a = np.array([1, 3, 0], float)
b = np.logical_and(a>0, a<3)

In [172]:
b

array([ True, False, False])

In [186]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [244]:
np.zeros(2)

array([0., 0.])

In [200]:
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [199]:
x=np.arange(10,50)
x=x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [205]:
x=np.arange(0,9).reshape(3,3)

x



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [263]:
### 6번 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를
###만드세요.
x=np.arange([1,2,0,0,4,0],int)
if np.any(x==0):
    print(x)
###### 수정

TypeError: unsupported operand type(s) for -: 'type' and 'list'

In [212]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [228]:
x=np.random.rand(3,3)
x

array([[0.32187262, 0.55964081, 0.86534558],
       [0.84728288, 0.10781717, 0.31631948],
       [0.40947866, 0.68708901, 0.70223529]])

In [231]:
np.min(x)

0.10781716598511137

In [233]:
np.max(x)

0.8653455811845067

In [264]:
np.mean(x,axis=0)

array([0.52621139, 0.45151566, 0.62796678])