In [2]:
import numpy as np

In [4]:
vector = np.zeros((10, ), int)
vector.size

10

In [6]:
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [8]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
x=np.arange(10,50)
x=x[::-1]
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [12]:
data = np.arange(0,9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
data = np.array([1,2,0,0,4,0], int)
condition =  data != 0
data[condition]

array([1, 2, 4])

In [16]:
matrix = np.identity((3), int)
matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
matrix = np.random.randn(3,3)
matrix

array([[-0.94300526, -0.72843618,  0.30776023],
       [-0.68502194,  0.00490491,  0.81355195],
       [ 0.48616428, -1.23406852,  0.15344946]])

In [21]:
matrix.max()

0.8135519500166547

In [23]:
matrix.min()

-1.234068520398374

In [25]:
matrix.mean(axis=1)

array([-0.4545604 ,  0.04447831, -0.19815159])

In [26]:
matrix.mean(axis=0)

array([-0.38062097, -0.65253326,  0.42492055])